version: "3"

volumes: 
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: stack/wordpress/volume/.
                        o: bind
                        type: none
        mariadb:
                name : mariadb
                driver: local
                driver_opts:
                        device: stack/mariadb/volume/.
                        o: bind
                        type: none
networks:
        inception:
                name: inception

services:
        nginx:
                container_name: nginx
                build: ./stack/nginx/.
                image: nginx:42
                ports: 
                - "443:443"
                depends_on: 
                - wordpress
                volumes: 
                - wordpress:/var/www/html
                networks: 
                - inception
                env_file: 
                - .env
                restart: always
        wordpress:
                container_name: wordpress
                build: ./stack/wordpress/.
                image: wordpress:42
                depends_on:
                - mariadb
                volumes: 
                - wordpress:/var/www/html
                env_file: 
                - .env
                networks: 
                - inception
                restart: always
        mariadb:
                container_name: mariadb
                build: ./stack/mariadb/.
                image: mariadb:42
                volumes: 
                - mariadb:/var/lib/mysql
                env_file: 
                - .env
                networks: 
                - inception
                restart: always
        